presubmits:

  kubernetes/ingress-nginx:
  - name: pull-ingress-nginx-boilerplate
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.go$|\.sh$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-boilerplate.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: boilerplate

  - name: pull-ingress-nginx-codegen
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.go$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-codegen.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: codegen

  - name: pull-ingress-nginx-gofmt
    always_run: false
    decorate: true
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.go$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-gofmt.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: gofmt

  - name: pull-ingress-nginx-golint
    always_run: false
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.go$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-golint.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: golint

  - name: pull-ingress-nginx-lualint
    always_run: false
    decorate: true
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.lua$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-lualint.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: lualint

  - name: pull-ingress-nginx-chart-lint
    always_run: false
    decorate: true
    decoration_config:
      timeout: 5m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: "^charts/"
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - ./hack/verify-chart-lint.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: chart-lint

  - name: pull-ingress-nginx-test-lua
    always_run: false
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.lua$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - make
        - lua-test
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: test-lua

  - name: pull-ingress-nginx-test
    always_run: false
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/ingress-nginx
    run_if_changed: '\.go$'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: k8s.gcr.io/ingress-nginx/e2e-test-runner:v20200904-gc2884a3da@sha256:f2de204dafb3951b974a53f7a4e9cc43b62b93c99b95edcb7a65afdc1d4f0bf4
        command:
        - /bin/bash
        - -c
        - "GIT_COMMIT=${PULL_PULL_SHA} make cover"
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: ingress-nginx-codecov-token
              key: ingress-nginx-codecov-token
    volumes:
    - name: ingress-nginx-codecov-token
      secret:
        secretName: ingress-nginx-codecov-token
        items:
        - key: ingress-nginx-codecov-token
          path: ingress-nginx-codecov-token
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: test

  - name: pull-ingress-nginx-e2e-1-15
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    #run_if_changed: '\.go$|^rootfs/'
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.15.11@sha256:6cc31f3533deb138792db2c7d1ffc36f7456a06f1db5556ad3b6927641016f50
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-1-15

  - name: pull-ingress-nginx-e2e-1-16
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    #run_if_changed: '\.go$|^rootfs/'
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-1-16

  - name: pull-ingress-nginx-e2e-1-17
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    #run_if_changed: '\.go$|^rootfs/'
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-1-17

  - name: pull-ingress-nginx-e2e-1-18
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    #run_if_changed: '\.go$|^rootfs/'
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.18.8@sha256:e1f5c7e498af9d2ff8e57c30db7bd9b20f6fd0b57be3aaa3f819ba491e359a58
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-1-18

  - name: pull-ingress-nginx-e2e-1-19
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    #run_if_changed: '\.go$|^rootfs/'
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.19.0@sha256:3b0289b2d1bab2cb9108645a006939d2f447a10ad2bb21919c332d06b548bbc6
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-1-19

  - name: pull-ingress-nginx-e2e-helm-chart
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5
    path_alias: k8s.io/ingress-nginx
    run_if_changed: "^charts/"
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
        command:
          - wrapper.sh
          - bash
          - -c
          - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-chart-tests
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        - name: REPO_INFO
          value: https://github.com/kubernetes/ingress-nginx
        - name: K8S_VERSION
          value: v1.19.0@sha256:3b0289b2d1bab2cb9108645a006939d2f447a10ad2bb21919c332d06b548bbc6
    annotations:
      testgrid-dashboards: sig-network-ingress-nginx
      testgrid-tab-name: e2e-helm-chart

periodics:
- name: ci-ingress-nginx-e2e
  interval: 12h
  max_concurrency: 1
  path_alias: k8s.io/ingress-nginx
  decorate: true
  decoration_config:
    timeout: 1h
  extra_refs:
  - org: kubernetes
    repo: ingress-nginx
    base_ref: master
    path_alias: k8s.io/ingress-nginx
  skip_submodules: true
  labels:
    preset-kind-volume-mounts: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/krte:v20200916-8dd1247-master
      command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      env:
      - name: REPO_INFO
        value: https://github.com/kubernetes/ingress-nginx
  annotations:
    testgrid-dashboards: sig-network-ingress-nginx
    testgrid-tab-name: ci-e2e
    testgrid-num-columns-recent: '20'
